parameters:
- name: environment
  type: string
- stage: Build
  jobs:
  - job: ${{parameters.environment}} deployment
    pool:
      name: Default
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: 'Build-$(Build.BuildNumber)'
        downloadPath: $(System.DefaultWorkingDirectory) 
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)/variableGroups'
        targetFiles: '**/templates/*.json'
        encoding: 'auto'
        tokenPattern: 'custom'
        tokenPrefix: '$('
        tokenSuffix: ')$'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        variableFiles: '**/parameters_${{parameters.environment}}$.json'
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: false
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Obtain list of parameter files from env directory
          $files = Get-ChildItem "$(Build.SourcesDirectory)/variableGroups/templates" | % { $_.FullName }
          Write-Host "##vso[task.setvariable variable=paramFiles;]$files"
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(paramFiles)