# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  dateToday: $(Get-Date -Format yyyyMMdd)

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Default

    steps:
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Build-$(Build.BuildNumber)'
        publishLocation: 'Container'

- template: azure-deployment-template.yml
  parameters: 
    environment: DEV
